//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.09.20 at 11:57:26 AM EDT 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://purl.oclc.org/dsdl/svrl", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED,
	xmlns = {
	        @XmlNs(prefix="svrl", namespaceURI="http://purl.oclc.org/dsdl/svrl")
	    }
)
package hp.hpfb.web.model;

import javax.xml.bind.annotation.XmlNs;
